### ISSUE TITLE
More customization?

### ISSUE THREAD

**Issue by ridvancelikcs** [YasuhiroABE/ub-autoinstall-iso#10]
Hi,

Is it possible to add other packages to the generated ISO that are not available in the /pool/ directory of the base ISO?
like tftp, net-snmp, tcpdump ... 
and also exclude some unnecessary packages to lighten the generated ISO.

What in my mind is 

- Exclude some packages (also dependent unneeded packages, like a functionality of autoremove)
- Include some packages with their dependencies in the ubuntu repos.
- Include my own deb packages.
- Post installation script which runs after the ISO installation on the target machine.

I don't know ubuntu installer chooses packages to install. 

Regards

**Comment by YasuhiroABE** [comment]
There are several way to implement these customizations.

If you don't have any specific restrictions, I recommend to edit your user-data file as follows.

- Install the minimum base image and additional packages using the "packages" section. (using "ubuntu-server-minimal")
- Execute post installation scripts with the "late-commands" section.
  - Remove unused packages
  - Install your deb packages

I placed my file, ubuntu.sudoers, as an example of placing files on the ISO image.
If your system is offline, you just place everything on your ISO file and run the post scripts.

If your system is online, I also recommend to use the ansible after installation to customize and manage your system with the minimum or a little modified base system. To use the ansible to manage your system is more universal method. The "user-data" customization is only way for the current ubuntu release.

FYI.
- https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall
