### ISSUE TITLE
How to install custom services in an image and then encapsulate them into an ISO image?

### ISSUE THREAD

**Issue by charnet1019** [YasuhiroABE/ub-autoinstall-iso#11]
Can I use this script to install some services in the image?
Can you provide an example if possible?
Thanks.

**Comment by YasuhiroABE** [comment]
You can place your script file into the iso_root/ directory and copy it into the /target directory as well as the iso_root/ubuntu.sudoers file.

I think that the curtin in-target command might be useful for customizing your installation.

* [https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#late-commands](https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html#late-commands)

Regards,

**Comment by charnet1019** [comment]
Thank you, resolved.
