### ISSUE TITLE
Sudoers approach in 24.04 LTS

### ISSUE THREAD

**Issue by scaleoutsean** [YasuhiroABE/ub-autoinstall-iso#16]
This doesn't seem to do much - I can't see that file and passwordless sudoing doesn't work either.

```yaml
  late-commands:
    - cp /cdrom/ubuntu.sudoers /target/etc/sudoers.d/99-user-ubuntu
```

Maybe using `user-data` [section](https://askubuntu.com/questions/1365637/autoinstall-user-datas-users-section-does-not-work-at-all) would be better?

**Comment by YasuhiroABE** [comment]
Hi,

If you don't need it, please delete these lines. 
The users section is a better place to manage users.

It's an example of how to copy some files into the iso image file; the sudoers file is placed in the config/extras/ directory and copied by the setup task of Makefile.

The settings are useful in some of my lab work. 
I never recommend using these settings if you set up a production server.
